# Auto-labeling configuration for pull requests
# Format for actions/labeler@v5

# Label based on modified files
dart:
  - changed-files:
    - any-glob-to-any-file: 'lib/**/*.dart'

code:
  - changed-files:
    - any-glob-to-any-file: 'lib/**/*.dart'

testing:
  - changed-files:
    - any-glob-to-any-file: 'test/**/*.dart'

ci/cd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

android:
  - changed-files:
    - any-glob-to-any-file: 'android/**'

ios:
  - changed-files:
    - any-glob-to-any-file: 'ios/**'

web:
  - changed-files:
    - any-glob-to-any-file: 'web/**'

linux:
  - changed-files:
    - any-glob-to-any-file: 'linux/**'

macos:
  - changed-files:
    - any-glob-to-any-file: 'macos/**'

windows:
  - changed-files:
    - any-glob-to-any-file: 'windows/**'

platform:
  - changed-files:
    - any-glob-to-any-file:
      - 'android/**'
      - 'ios/**'
      - 'web/**'
      - 'linux/**'
      - 'macos/**'
      - 'windows/**'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'pubspec.yaml'

configuration:
  - changed-files:
    - any-glob-to-any-file: 'analysis_options.yaml'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'lib/screens/**'
      - 'lib/widgets/**'

screens:
  - changed-files:
    - any-glob-to-any-file: 'lib/screens/**'

widgets:
  - changed-files:
    - any-glob-to-any-file: 'lib/widgets/**'

state-management:
  - changed-files:
    - any-glob-to-any-file: 'lib/providers/**'

models:
  - changed-files:
    - any-glob-to-any-file: 'lib/models/**'

services:
  - changed-files:
    - any-glob-to-any-file: 'lib/services/**'

repositories:
  - changed-files:
    - any-glob-to-any-file: 'lib/repositories/**'

